<a href="https://colab.research.google.com/github/anvesh-vankayala/PyTorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.1.0+cu121'

**Scalar**

In [ ]:
## Scalar is just a single number
scalar = torch.tensor(7)
print('n dimension : ', scalar.ndim)
print('To retrive value from tensor : ', scalar.item())
print('Just tensor : ' , scalar)

shape :  0
To retrive value from tensor :  7
Just tensor :  tensor(7)


**Vector**

In [ ]:
## Vector is a single dimension tensor
vector = torch.tensor([2,5,6])
print('n dimension : ', vector.ndim)
print('shape : ', vector.shape)
#print('To retrive value from tensor : ', vector.item())
print('Just tensor : ' , vector)

print('---------------------')
## Matrix
matrix  = torch.tensor([[2,4,6],[3,7,8]])
print('ndim', matrix.ndim)
print('shape : ', matrix.shape)
print('dtype : ', matrix.dtype)
print('Just tensor : ' , matrix)

print('---------------------')

## Random tensor
tensors = torch.rand(size=[3,4])
print('ndim', tensors.ndim)
print('dtype : ', tensors.dtype)
print('shape : ', tensors.shape)
print('Just tensor : ' , tensors)

print('---------------------')
## Random image tensor
rand_img = torch.rand(size= (224,224,3))
print('ndim', rand_img.ndim)
print('Random image tensor shape : ', rand_img.shape)

print('---------------------')

n dimension :  1
shape :  torch.Size([3])
Just tensor :  tensor([2, 5, 6])
---------------------
ndim 2
shape :  torch.Size([2, 3])
dtype :  torch.int64
Just tensor :  tensor([[2, 4, 6],
        [3, 7, 8]])
---------------------
ndim 2
dtype :  torch.float32
shape :  torch.Size([3, 4])
Just tensor :  tensor([[0.1731, 0.0179, 0.1396, 0.7403],
        [0.5782, 0.4061, 0.5233, 0.7060],
        [0.9326, 0.0890, 0.6658, 0.5490]])
---------------------
ndim 3
Random image tensor shape :  torch.Size([224, 224, 3])


**Info from tensors**

In [ ]:
tensor = torch.rand(size=[3,4])
print(f'shape : {tensor.shape}')
print(f'dtype : {tensor.dtype}')
print(f'device : {tensor.device}')

shape : torch.Size([3, 4])
dtype : torch.float32
device : cpu


**Manipulating** **tensors**

In [ ]:
## Addition

tensor = torch.tensor([1,2,3])
print(f'Addition : {tensor + 10}')
print(f'Mutiplication : {tensor * 10}')
print(f'subtraction : {tensor - 10}')
print(f'Element wise multiplication : {tensor * tensor}')
## Note : Tensor dosent get modified unless it is reassigned

## Matrix multiplication
## To work : this should have inner same inner diemension
## ex shapes : If input is of shape (3,2)@(2,4) , then output would be of (3,3)

print(f'Matrix multiplication : {torch.matmul(tensor,tensor)}')
print(f'with @ Matrix multiplication : {tensor@tensor}')

print('---------------------------')

## Matrix transpose
## If there is any issue with inner shape of tensor,  with this we can switch the shape of tensor.
ran_tensor = torch.rand(4,5)
print(f'shape {ran_tensor.shape}')
print(f'Transposed tensor {ran_tensor.T.shape}')
print(f'Matrix multiplication \n {ran_tensor@ran_tensor.T} , of shape {(ran_tensor@ran_tensor.T).shape}')

print('---------------------------')

## as linear layer initiates with random weights, to reproduce result setting the seed.
torch.manual_seed(42)

linear = torch.nn.Linear(in_features = 2, out_features = 6)

## Note : inner dimension of the in_feature should match with the input tensor
x = torch.tensor([[1,2],[4,5],[6,7]] , dtype = torch.float32)
print(f'Input tensor shape : {x.shape}')
output = linear(x)
print(f'Output tensor shape : {output.shape}')
print(f'Output tensor : \n {output}')

print('---------------------------')

## changing tensor data types
tensor = torch.tensor([[2,4],[7,8]],dtype= torch.float16)
print(f'data type {tensor.dtype}')
print(f'data type changing {tensor.type(torch.float32).dtype}')

print('---------------------------')



Addition : tensor([11, 12, 13])
Mutiplication : tensor([10, 20, 30])
subtraction : tensor([-9, -8, -7])
Element wise multiplication : tensor([1, 4, 9])
Matrix multiplication : 14
with @ Matrix multiplication : 14
---------------------------
shape torch.Size([4, 5])
Transposed tensor torch.Size([5, 4])
Matrix multiplication 
 tensor([[0.8204, 0.5780, 0.7026, 1.1089],
        [0.5780, 0.9439, 0.9158, 1.1262],
        [0.7026, 0.9158, 1.9956, 1.9354],
        [1.1089, 1.1262, 1.9354, 2.2598]]) , of shape torch.Size([4, 4])
---------------------------
Input tensor shape : torch.Size([3, 2])
Output tensor shape : torch.Size([3, 6])
Output tensor : 
 tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [5.6194, 2.6809, 0.4347, 0.5995, 0.4447, 3.2247],
        [7.8744, 3.6487, 0.4102, 0.7415, 0.6539, 4.7186]],
       grad_fn=<AddmmBackward0>)
---------------------------
data type torch.float16
data type torch.float32


**Reshaping/Stacking/Sqeezing/unsqeezing/view**

In [11]:
import torch
x = torch.arange(1,8)
print(f'Orginal shape {x.shape}')
print(f'unsqeezed shape at dim=0 : {x.unsqueeze(dim=0)} , shape -  {x.unsqueeze(dim=0).shape}')
print(f'unsqeezed shape at dim=1 : {x.unsqueeze(dim=1)} , shape - {x.unsqueeze(dim=1).shape}')
print(f'unsqeezed shape at dim=1 : {x.unsqueeze(dim=0).unsqueeze(dim=1)} , shape - {x.unsqueeze(dim=0).unsqueeze(dim=1).shape}')

print('--------------------------------')



Orginal shape torch.Size([7])
unsqeezed shape at dim=0 : tensor([[1, 2, 3, 4, 5, 6, 7]]) , shape -  torch.Size([1, 7])
unsqeezed shape at dim=1 : tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]]) , shape - torch.Size([7, 1])
unsqeezed shape at dim=1 : tensor([[[1, 2, 3, 4, 5, 6, 7]]]) , shape - torch.Size([1, 1, 7])
--------------------------------


In [29]:
import torch

t = torch.arange(1,9)
print(f'tensor : {t}')
print(f'Reshaped tensor : {t.reshape(2,4)}')
print(f'Unsqueezed tensor : {t.unsqueeze(dim=0)}')
print(f'Tensor view at shape 2,4 : {t.view(2,4)}')
ut = t.unsqueeze(dim=0)
print(f'Unsqeezed tensor :  {ut}')

tensor : tensor([1, 2, 3, 4, 5, 6, 7, 8])
Reshaped tensor : tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
Unsqueezed tensor : tensor([[1, 2, 3, 4, 5, 6, 7, 8]])
Tensor view at shape 2,4 : tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
Unsqeezed tensor :  tensor([[1, 2, 3, 4, 5, 6, 7, 8]])


In [59]:
c = torch.arange(0,24)
c = c.reshape(2,3,4)
print(c.shape)
print(c.dim())
print(c)
c[:,:,:2] = 0
print('----------------------------------')
c

torch.Size([2, 3, 4])
3
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
----------------------------------


tensor([[[ 0,  0,  2,  3],
         [ 0,  0,  6,  7],
         [ 0,  0, 10, 11]],

        [[ 0,  0, 14, 15],
         [ 0,  0, 18, 19],
         [ 0,  0, 22, 23]]])

In [64]:
t = torch.arange(1,8)
print(f'Dim 0 stack {torch.stack([t,t,t,t],dim=0)}')
print(f'Dim 1 stack {torch.stack([t,t,t,t],dim=1)}')


Dim 0 stack tensor([[1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7]])
Dim 1 stack tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7]])


In [68]:
t = torch.arange(0,12)
t1 = t.reshape(3,4)
dim0 = torch.stack([t1,t1],dim = 0)
print(dim0, dim0.shape)
print('--------------------------------')
dim1 = torch.stack([t1,t1],dim = 1)
print(dim1,dim1.shape)
print('--------------------------------')
dim1 = torch.stack([t1,t1],dim = 2)
print(dim1,dim1.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]]) torch.Size([2, 3, 4])
--------------------------------
tensor([[[ 0,  1,  2,  3],
         [ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [ 8,  9, 10, 11]]]) torch.Size([3, 2, 4])
--------------------------------
tensor([[[ 0,  0],
         [ 1,  1],
         [ 2,  2],
         [ 3,  3]],

        [[ 4,  4],
         [ 5,  5],
         [ 6,  6],
         [ 7,  7]],

        [[ 8,  8],
         [ 9,  9],
         [10, 10],
         [11, 11]]]) torch.Size([3, 4, 2])


### **Tensors with Numpy**

In [72]:
import numpy as np
import torch

ar = np.arange(2,3)
print(f' {ar}')
ar = torch.from_numpy(ar)
print(f' {ar}')
print(f' {ar.numpy()}')

 [2]
 tensor([2])
 [2]


### **Reproducibility - (trying seed random)**

In [79]:
import torch

r1 = torch.rand(3,4)
r2 = torch.rand(3,4)
print(r1)
print(r2)
print(r1==r2)
print('_________________________')

torch.manual_seed(seed=23)

r1 = torch.rand(3,4)

torch.manual_seed(seed=23)
r2 = torch.rand(3,4)
print(r1)
print(r2)
print(r1==r2)


tensor([[0.5466, 0.0213, 0.9049, 0.8444],
        [0.9330, 0.2950, 0.4773, 0.4787],
        [0.3440, 0.6732, 0.6593, 0.1879]])
tensor([[0.4546, 0.1049, 0.7112, 0.7709],
        [0.5514, 0.0807, 0.3029, 0.7935],
        [0.2823, 0.5686, 0.1354, 0.4224]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
_________________________
tensor([[0.4283, 0.2889, 0.4224, 0.3571],
        [0.9577, 0.1100, 0.2933, 0.9205],
        [0.5876, 0.1299, 0.6729, 0.1028]])
tensor([[0.4283, 0.2889, 0.4224, 0.3571],
        [0.9577, 0.1100, 0.2933, 0.9205],
        [0.5876, 0.1299, 0.6729, 0.1028]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [12]:
import torch
tr = torch.rand(2,3)
print(f'GPU device count :  {torch.cuda.device_count()}')
print(f'Is GPU available : {torch.cuda.is_available()}')
tr = tr.to('cuda')
tr

GPU device count :  1
Is GPU available : True


tensor([[0.3749, 0.8229, 0.5056],
        [0.6932, 0.0452, 0.2679]], device='cuda:0')

tensor([[0.7836, 0.2809, 0.9722],
        [0.8046, 0.0558, 0.5501]])